# Generated by Django 5.1.1 on 2024-09-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fruits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruit_name", models.CharField(max_length=50)),
                ("fruit_image", models.ImageField(upload_to="images/")),
                ("fruit_description", models.TextField()),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
