# Generated by Django 5.1.1 on 2024-09-26 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="fruits",
            new_name="fruits_data",
        ),
    ]
