# Generated by Django 5.1.2 on 2024-10-15 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_car"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Car",
            new_name="Cars",
        ),
    ]
