# Generated by Django 5.1.2 on 2024-10-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="estimated_time",
        ),
        migrations.AddField(
            model_name="recipes",
            name="recipe_img",
            field=models.ImageField(null=True, upload_to="Recipe_img"),
        ),
    ]
